baseURL = 'http://aidaaminian.github.io/'
languageCode = 'en-us'
title = 'Aida Aminian'



[Params]


[Params.Navbar]
use = false

[Params.Terminal]
scheme = "shell-ubuntu"
userName = "Aminian"
pcName = "laptop"
workDir = "mydir"
profile = "profile.txt"


description = """
Hi, I am Aida Aminian!
Nice to meet you.
"""

[Params.Tree]
use = true
folderName = "contact_info"

files = [
    [ "email", "mailto:aida.aminian1@gmail.com"],
    [ "github", "https://github.com/aidaaminian"],
    [ "Linkedin", "https://www.linkedin.com/in/aida-aminian-36b363245"]
]



